# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170711_0159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_no',
            new_name='phone',
        ),
    ]
