# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170711_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userwee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('age', models.ImageField(default=0, upload_to=b'')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('has_verfied_mobile', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
