# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20170711_0215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userwee',
            new_name='User',
        ),
    ]
