# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20170711_0231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='has_verfied_mobile',
            new_name='has_verified_mobile',
        ),
    ]
