# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_postmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='imsage',
            new_name='image',
        ),
    ]
