# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20170721_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='has_upvote',
            field=models.BooleanField(default=False),
        ),
    ]
